import random
facts = [
    "The English word for red panda is ‘Firefox’ which is where the browser gets its name from – this means the Firefox logo is actually a red panda, not a fox!",
"In 1994, the company who had a patent on GIFs tried to charge a fee for using GIFS. The PNG was invented as an alternative, and the company backed down.",
"The very first Apple logo featured Sir Isaac Newton sitting underneath a tree, with an apple about to hit his head.",
"Google rents out goats from a company called California Grazing to help cut down the amount of weeds and brush at Google HQ!",
"The founder of Microsoft, Bill Gates, was a college drop out.",
"Bill Gates house was designed using a Macintosh Computer.",
"The word robot comes from the Czech “robota“. This translates into forced labor, or work.",
"CD’s (Compact discs) read from the inside to the outside edge, which is the reverse of how records work.",
"You cannot reverse a Bitcoin transaction, or be forced to pay.",
"The average computer user blinks seven times a minute, the normal rate is twenty times per minute.",
"The first ever VCR (Video Camera Recorder), which was made in 1956, was the size of a piano!",
"On an average work day, a typist’s fingers travel about 12.6 miles.",
"The 30th of November is known as “Computer Security Day“.",
"On 1st April 2005, NASA pulled a prank telling the world that they had found water on Mars.",
"The radio took 38 years to reach a market audience of 50 million. The television took 13 years and the iPod only took 3 years to reach a market audience of 50 million.",
"Using a hands-free device to talk on the phone while driving is shown to be equally or more dangerous than driving drunk.",
"If you were to have your picture taken by the very first camera, you’d need to sit still for 8 hours.",
"A dentist named Alfred Southwick invented the electric chair.",
"The creators of the PNG file format wanted it to be pronounced as ‘ping’.",
"Credit card EMV chip technology has been around since 1986. It was first implemented in France, with Germany following shortly after.",
"Alaska is the only state in America that can be typed on one row of a traditional English QWERTY keyboard.",
"The Apple II had a hard drive of only 5 megabytes when it was launched in June 1977.",
"Q33 was the first plane to hit during 9/11 in 2001, when you type in Q33 in Microsoft’s Wingding’s font, a very sinister thing appears; Q33",
"In general, people tend to read as much as 10% slower from a screen than from paper.",
"Although GPS is free for the world to use, it costs $2 million per day to operate. The money comes from American tax revenue.",
"There are computers designed for Amish people, with selling points like “No internet, no video, no music”.",
"Ubuntu is one of the more popular distributions of Linux. The word Ubuntu comes from an African word meaning “I am because of you”.",
"The Name “Macintosh” Was Inspired by an Apple with the name “mcintosh”.",
"Christopher Sholes invented the QWERTY keyboard in 1868. In 1932 Professor August Dvorak created the Dvorak keyboard, which was made to be superior to the standard QWERTY keyboard.",
"Doug Engelbart created the very first computer mouse from wood in 1964.",
"Spam mail got its name from the canned meat after a Monty Python skit that made fun of Spam as tasting “horrible and being ubiquitous and inescapable.”",
"In June 1983, the Apple Lisa was released; it was the first commercial computer with a graphical user interface (GUI) and a mouse.",
"The original Xbox contained edited snippets of actual transmissions from the Apollo missions.",
"In 1822, Charles Babbage created the first computer.",
"1024 Gigabytes is equal to 1 Terabyte. 1024 Terabytes is equal to 1 Petabyte, and 1 Petabyte can hold 13.3 years of HD-TV video.",
"86% of people try to plug their USB devices upside down.",
"The last game for the Sega Mega Drive was released in 2010 and was so popular it sold out before release.",
"During the first live iPhone presentation, Steve Jobs had to frequently switch phones behind his desk. Otherwise, it would run out of RAM and crash.",
"The first alarm clock could only ring at 4 a.m.",
"A Welshman threw away a hard drive containing a staggering sum of 7,500 bitcoins. The sum equates to almost $32 million and the man will never be able to retrieve it as it was already buried under a hefty 25,000 cubic meters of rubbish in 2013.",
"The average age of gamers in the United States is 35.",
"In 2010, the United States Air Force used 1,760 PlayStation 3’s to build a supercomputer for the Department of Defense. They used PS3’s because it was more cost efficient and “green”.",
"The Sega Dreamcast was the first 128-bit console in the market. It was released in 1999 and was the first console which allowed real-time online play.",
"Surgeons who grew up playing video games make 37% fewer mistakes.",
"Nintendo was started in 1889 as a playing card company.",
"The astronauts of Apollo 11 couldn’t get life insurance, so instead they signed photos that their families could auction in case the landing went wrong.",
"In January 2007, the PS3 DualShock controller won an Emmy Award for ‘Peripheral Development and Technological Impact of Video Game Controllers’ by The National Academy of Television Arts & Sciences.",
"In mobile games, 60% of all revenue came from only 0.23% of players.",
"When signing up to iTunes, if you accept their Terms & Conditions, you agree to not use it to make nuclear weapons.",
"2.1 million people still use AOL 56k dial-up in the U.S.",
"The Atari 2600 was originally called “Atari Video Computer System”, or “VCS”.",
"When Snapchat launched in 2011, it was named Picaboo, but in 2012, it was renamed to Snapchat.",
"In 2004, the “at” symbol used in emails (@) became the first new character to be added to Morse code in several decades! The new character, known as the “Commat” consists of the signals for both A (dot-dash), and C (dash-dot-dash-dot) with no space or break in between.",
"The very first domain name registered was www.symbolics.com, on the 15th March, 1985.",
"According to the Message Anti-Abuse Working Group, between 88% and 92% of all emails that were sent in the first half of 2010 were spam.",
"Anthony Greco was the first man ever arrested for sending spam messages in 2005.",
"In May 2017, Samsung were given permission to carry out trials of a self-driving car in South Korea.",
"All the letter combinations from aaa.com to zzz.com have already been registered.",
"On eBay, there is an average of $680 worth of transactions every second.",
"It is estimated that spammers only receive 1 reply for every 12 million emails that they send out.",
"The domain name www.YouTube.com was registered 14th February 2005.",
"Amazon now sells more eBooks than it does printed books!",
"Amazon.com was previously known as Cadabra.com.",
"The first ever Internet Service Provider (ISP) was a company named CompuServe.",
"The original URL for Yahoo was http://akebono.stanford.edu",
"The name Yahoo was created by Jonathan Swift for his book Gulliver’s Travels (1726) – which explained a “yahoo” to be a really ugly person.",
"Klingon was added as a Google language option in 2002.",
"The first country to build drones was Israel, with Israel Aerospace Industries heading the charge in terms of export numbers.",
"In 1984, the number of internet devices reached 1,000. By 1992, it reached 1 million, and in 2008, the number of internet devices reached 1 billion!",
"In 1999, PayPal was voted as one of the top ten worst business ideas.",
"97% of people type in random words on Google, just to see if they spelled it right.",
"There are over 35 billion Google searches every month.",
"The first word that was ever auto-corrected was “teh” to “the”. You corrected it by pressing the left arrow and F3.",
"In 1993, Soviet cosmonaut Aleksandr A. Serebrov took his Nintendo Game Boy to space, on the TM-17 space mission. Later, it was auctioned for $1,220 and is said to have orbited Earth 3,000 times.",
"The word “Android” means a human with a male robot appearance.",
"In 2000, the FIFA 2001 game used Scratch & Sniff technology on their discs; it had the scent of a football stadium turf on the disc.",
"Phantom Vibration Syndrome is the name given when someone thinks their phone is vibrating but isn’t.",
"The Comic Sans font is widely known as the world’s most hated font.",
"Apple have a ‘no smoking’ ban regarding their computers, which means if you smoke while using an Apple computer, you void the warranty.",
"Using your phone while it is on charge can damage the battery; this is why the leads for the chargers are so short.",
"vIn 1973, the very first mobile phone call was made by Martin Cooper, who was an employee of Motorola. The call was made from the streets of New York City.",
"Nokia was founded in 1865 and its primary business was manufacturing paper. Nokia’s first mobile phones were released in the 1980’s.",
"The first commercial text message was sent in December 1992.",
"Technophobia is the fear of technology.",
"Almost half the world’s population has never made a phone call.",
"There are Braille accessories for smart phones.",
"The most expensive number ever sold was a mobile phone number, 666-6666, which was put up for auction and sold for $2.7 million!",
"Originally, the design for the first iPhone was literally the shape of an apple.",
"Facebook has a blue color scheme because the creator, Mark Zuckerberg cannot see the colors red & green.",
"Around 20% of all YouTube videos are music related.",
"If you find a security bug in Facebook’s code, they are willing to pay from $500 for you to tell them about it!",
"It is estimated that one in every eight couples in the U.S. who went on to marry each other met online.",
"Someone on Twitter who has a million or more followers is known as a “Twillionaire”.",
"In the 1990’s, the Japanese company Hitachi-Omron Terminal Solutions created an ATM machine that heats bills to 200°C so that bacteria is killed before dispensing them.",
"Google’s first ever Tweet on Twitter was in February 2009, and reads “I’m 01100110 01100101 01100101 01101100 01101001 01101110 01100111 00100000 01101100 01110101 01100011 01101011 01111001 00001010.” Translating from binary into English, this tweet says “I’m feeling lucky.”",
"Google+ was developed under the code name ‘Emerald Sea’.",
"Remember MySpace? Well it still has over 200 million registered users.",
"Facebook took 2 years to reach a market audience of 50 million.",
"60% of LinkedIn members have clicked one of their adverts.",
"Spending 1 hour a day on Social Media reduces the probability of a child being completely happy with their life by 14%."
        ]


random_fact = random.choice(facts)


print(f"{random_fact}") 